name: workflow to deploy an ARM Template to a Management Group Scope
on: push

# CONFIGURATION
# For help, go to https://github.com/Azure/Actions

env:
  AZURE_MANAGEMENT_GROUP_ID: << Management Group Id >>   # set this to your Azure Management Group Id
  
jobs:
  build-and-deploy-to-dev:
    runs-on: ubuntu-latest
    steps:
                
    # Set up the following secrets in your repository: AZURE_CREDENTIALS
    # Ensure that the SPN has contributor access to Management Group, please refer https://docs.microsoft.com/en-us/azure/governance/management-groups/manage
    # For details on usage of secrets, please refer https://help.github.com/en/actions/configuring-and-managing-workflows/creating-and-storing-encrypted-secrets
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS  }}
    
    # Checkout
    - name: Checkout
      uses: actions/checkout@v1
        
    # Deployment of template    
    - name: Deploy ARM Template
      uses: azure/arm-deploy@v1
      with:
        # You can change these environment variables for your configuration: AZURE_SUBSCRIPTION_ID
        scope: managementgroup
        managementGroupId: ${{ env.AZURE_MANAGEMENT_GROUP_ID }}
        region: centralus # Set this to your target region
        template: $GITHUB_WORKSPACE/azuredeploy.json  # Set this to the location of your template file
        parameters: $GITHUB_WORKSPACE/azuredeploy.parameters.json # Set this to the location of your parameters file
